# Generated by Django 3.0.5 on 2020-11-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('FullCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Index', models.IntegerField(max_length=5)),
                ('Title', models.CharField(blank=True, max_length=500, null=True)),
                ('Instructors', models.CharField(max_length=500)),
                ('Credits', models.IntegerField(default=0)),
                ('MeetingType', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.BooleanField(default=True)),
                ('Enrolled', models.IntegerField(blank=True, null=True)),
                ('Capacity', models.IntegerField(blank=True, null=True)),
                ('MeetingTimes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.IntegerField(blank=True, max_length=6, null=True)),
                ('RUID', models.IntegerField(blank=True, max_length=50, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(blank=True, max_length=50, null=True)),
                ('DegreeLevel', models.CharField(blank=True, max_length=50, null=True)),
                ('CreditsRegistered', models.IntegerField(blank=True, max_length=15, null=True)),
                ('CreditsTaken', models.IntegerField(blank=True, max_length=15, null=True)),
                ('CoursesRegistered', models.IntegerField(blank=True, max_length=15, null=True)),
                ('CoursesTaken', models.IntegerField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
