# Generated by Django 3.0.5 on 2020-11-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Index', models.IntegerField()),
                ('FullCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Instructors', models.CharField(max_length=500)),
                ('Status', models.CharField(max_length=10)),
                ('MeetingTimes', models.CharField(max_length=100)),
                ('Capacity', models.IntegerField()),
                ('Enrolled', models.IntegerField()),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(max_length=50)),
                ('netId', models.IntegerField()),
                ('ruId', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('gradelevel', models.CharField(max_length=50)),
                ('CoursesTaken', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
