# Generated by Django 3.0.5 on 2020-11-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.IntegerField()),
                ('sectionNumber', models.CharField(max_length=3)),
                ('Index', models.IntegerField(primary_key=True, serialize=False)),
                ('Instructors', models.TextField()),
                ('Title', models.TextField()),
                ('Credits', models.IntegerField()),
                ('MeetingType', models.CharField(max_length=20)),
                ('Status', models.BooleanField()),
                ('Enrolled', models.IntegerField()),
                ('Capacity', models.IntegerField()),
                ('MeetingTimes', models.TextField()),
                ('Prerequisites', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('netID', models.TextField(primary_key=True, serialize=False)),
                ('RUID', models.IntegerField()),
                ('FirstName', models.TextField()),
                ('LastName', models.TextField()),
                ('DegreeLevel', models.CharField(max_length=2)),
                ('CreditsRegistered', models.IntegerField()),
                ('CreditsTaken', models.IntegerField()),
                ('CoursesRegistered', models.IntegerField()),
                ('CoursesTaken', models.IntegerField()),
            ],
        ),
    ]
