# Generated by Django 3.0.5 on 2020-11-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myR', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
