# Generated by Django 3.0.5 on 2020-11-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='CoursesRegistered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='CoursesTaken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='CreditsRegistered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='CreditsTaken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='RUID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='netid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
