# Generated by Django 3.0.5 on 2020-11-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myR', '0003_auto_20201108_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Credits',
            new_name='courseCredits',
        ),
    ]
